apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nexus-landing
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        # Limit memory and CPU for cost optimization
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1000m"
        # Enable HTTP/2 for better performance
        run.googleapis.com/execution-environment: gen2
        # Set max instances for cost control
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - image: REPLACE_WITH_IMAGE_URL
        ports:
        - name: http1
          containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        # Health check for better reliability
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
  traffic:
  - percent: 100
    latestRevision: true